INSERT INTO LOCATIONS VALUES(1, 'Splai', '999', 'Bucuresti','Romania');
INSERT INTO DEPARTMENTS VALUES(1, 'ADMINISTRATION', 1);
INSERT INTO JOBS VALUES (1, 'ADMINISTRATION', 999, 9999);
INSERT INTO EMPLOYEES VALUES (1, 'Adi', 'Gheorghe', 'mail', '056.342', now(), 1, 2000, NULL, NULL, 1);