
DROP TABLE LOCATIONS;
CREATE TABLE LOCATIONS (
  LOCATION_ID INT PRIMARY KEY,
  STREET_ADDRESS VARCHAR(40),
  POSTAL_CODE VARCHAR(12),
  CITY VARCHAR(30) NOT NULL,
  STATE_PROVENCE VARCHAR(25)
);

DROP TABLE DEPARTMENTS;
CREATE TABLE DEPARTMENTS(
  DEPARTAMENT_ID INT PRIMARY KEY,
  DEPARTAMENT_NAME VARCHAR(30),
  LOCATION_ID INT
);

DROP TABLE JOBS;
CREATE TABLE JOBS(
  JOB_ID INT PRIMARY KEY,
  JOB_TITLE VARCHAR(35),
  MIN_SALARY INT,
  MAX_SALARY INT
);

DROP TABLE EMPLOYEES;
CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(20),
  LAST_NAME VARCHAR(25) NOT NULL,
  EMAIL VARCHAR(25) NOT NULL,
  PHONE_NUMBER VARCHAR(20),
  HIRE_DATE DATE NOT NULL,
  JOB_ID INT NOT NULL,
  SALARY DECIMAL(8, 2),
  COMMISION_PCT DECIMAL(2, 2),
  MANAGER_ID INT,
  DEPARTAMENT_ID INT
);
